### ISSUE TITLE
Admin backbone - P0 functions

### ISSUE THREAD

**Issue by tanguy2m** [tanguy2m/RN6-WebApps#1]
Functions covered:
- rntoolbox package
- Admin share
- MySQL admin (root pwd & share)
- **API** > backbone (utilities and router)
- **API** > PHP CLI entry point
- **Toolbox HMI** > backbone and log retrieval

***TODO***

- [x] Log file shall be kept even after a rntoolbox purge
- [x] Remove toolbox custo
- [x] rntoolbox purge shall reset everything
- [x] Errors on install:
```
Setting up rntoolbox (0.1.0) ...
tr: write error: Broken pipe
tr: write error
/var/lib/dpkg/info/rntoolbox.postinst: 49: /var/lib/dpkg/info/rntoolbox.postinst: cannot create ~/.my.cnf: Directory nonexistent
chmod: cannot access '~/.my.cnf': No such file or directory
```
- [x] **rntoolbox postinst** > If ~/.my.cnf existe, check root pwd and raise error if not correct
- [ ] May not be necessary to copy sample setup file
- [ ] **API & Toolbox HMI** > Feedback when a file is saved
- [ ] **Log* > Periodic refresh (using http headers)
- [ ] /apps/toolbox shall be accessible only to admin
- [ ] Samba access to admin share useful ? If yes, modify samba config to give access only to admin group

**Comment by tanguy2m** [comment]
***DESIGN***

**Admin share structure**
```
//admin
    |_ backup
    |_ config (kept when package is installed / updated)
    |    |_ webapp1
    |    |    |_ conf.inc.php
    |    |    |_ conf.inc.php.original
    |    |_ webapp2
    |_ factory
    |    |_ webapp_package.json (if no other file necessary)
    |    |_ webapp
    |        |_ package.json
    |        |_ postinst_script.sh
    |        |_ logo.png
    |        |_ rnwebapp_0.x.y_all.deb
    |_ setup (not kept when package is installed / updated)
        |_ webapp
            |_ setup.json
            |_ postinst_script.sh
```
