### ISSUE TITLE
Web-apps packages generation - P0 functions

### ISSUE THREAD

**Issue by tanguy2m** [tanguy2m/RN6-WebApps#2]
Functions covered:
- **Skeleton**: all files different from DEBIAN install/desinstall scripts
- Factory set-up: folder, sample file
- **API & HMI** > packages generation
- **API** > packages setup listing
- **API & HMI** > packages setup files edition

**TODO**

_P0_
- [x] Display something when no file is found
- [x] **Toolbox HMI/API**: allow creation of new set-up file
- [ ] Improve the layout of the panel
```diff
- Current
```
![capture](https://cloud.githubusercontent.com/assets/1895945/22065082/cc4cd204-dd86-11e6-9aa2-2c68b32228fd.PNG)
```diff
+ Proposals
```
![1484749736005](https://cloud.githubusercontent.com/assets/1895945/22067891/641a59ec-dd93-11e6-8b2f-6d41caa3c6ac.jpg)
- [ ] **HMI & API**: allow files upload (e.g archive, logo) in the set-up folder from the set-up panel
- [ ] **HMI & API**: allow files cloning from GitHub
- [ ] //admin/factory => chmod 775
- [ ] **API**: manage error on previous generation (copied skeleton folder still exists)
- [ ] **API**: create a package setup verification function (called twice: before display & before generation)

_P1_
- [ ] **HMI & API**: Allow set-up folder deletion from the panel
- [ ] Allow archive upload `APPNAME.zip` containing the files through toolbox HMI

_P2_
- [ ] Add a web form to set-up a package

**Comment by tanguy2m** [comment]
**DESIGN**

.deb package chosen for the following reasons:
- Installation scripts executed by root (useful for MySQL database creation)
- Dependencies are installed (no manual use of apt-get)
- Apache config file is managed by ReadyNAS

ReadyNAS OS6 SDK: http://apps.readynas.com/pages/?page_id=68
Readme: http://apps.readynas.com/pages/?page_id=90

Target = allow end-to-end package creation **without SSH or Samba access.**

**Comment by tanguy2m** [comment]
**README**

Files to be provided:
- `package.json` containing all data to build the package + the setup data (future `setup.json`)
- _OPTIONAL_ `logo.png` 150x150px PNG
- _OPTIONAL_ archive containing web files
- _OPTIONAL_ postinst script declared in `package.json`

To be uploaded in:  `//admin/factory` (automatic listing of files ending with package.json)
