### ISSUE TITLE
Web-apps installation / uninstallation - P0 functions

### ISSUE THREAD

**Issue by tanguy2m** [tanguy2m/RN6-WebApps#3]
Functions covered:
- **Skeleton**: DEBIAN install/desinstall scripts
- Web-app Apache config
- **API** > install packages
- **API** > list packages
- **Toolbox HMI** > packages installation

***TODO***
- [x] Display something when no file is found
- [ ] **API**: keep archive when install is successful
- [ ] **HMI**: improve feedback on install (download & extract can be a long task)
- [ ] Create a "repository" folder on admin share to store all the archives ?
- [ ] ReadyNAS notifications are not displayed
- [ ] **API**: manage _tar_ or _git_ deployment modes
- Logs improvement
  - [ ] Skeleton: log when install begins (preinst?)
  - [ ] General amelioration of postinst logs

**Comment by tanguy2m** [comment]
***DESIGN***

**Folders**

|  | Creation | Removal |
|------------------|----------|---------|
| **Config, Setup & Web** | **postinst** *configure* | **postrm** *purge* |
| **MySQL** | **postinst** *configure* (calling **toolbox/mysql.sh** *create*) | **postrm** *purge* (calling **toolbox/mysql.sh** *remove*) |

**Files**

|  | Creation | Modification | Removal |
|--|----------|----------------|----------|
| **Config files** | **API:** PUT */apps/APPLI/files/all* (First call by **postinst** *configure*) | **API:** PUT */apps/APPLI/files/conf/FILE* | **API:** DELETE */apps/APPLI/files/all* (First call by **postrm** *purge*)  |
| **https.conf** | Included in package | Not possible through toolbox or via Samba. Only via ssh or new package version. | Done by Debian on removal |
| **Setup files** | Common with config | **API:** PUT */apps/APPLI/files/setup/FILE* | Common with config |
| **Web files** | Common with config | Not possible through toolbox or via Samba. Only via ssh or new package version. | **TO BE CLARIFIED** prerm remove / API remove / porstrm remove => API remove? |

**Apache configuration file reference**
- ReadyNas OS 4 file `/etc/frontview/apache/Auth.conf`

``` apache
<IfModule authnz_external_module>
    AuthType Basic
    AuthBasicProvider external
    AuthExternal pwauth
</IfModule>

<IfModule !authnz_external_module>
    LoadModule authnz_external_module /usr/lib/apache2/modules/mod_authnz_external.so
    LoadModule auth_sys_group_module /usr/lib/apache2/modules/mod_auth_sys_group.so
    AddExternalAuth pwauth /usr/bin/pwauth
    SetExternalAuthMethod pwauth environment
</IfModule>
```
- ReadyNas OS 6 file `/etc/frontview/apache/Auth.conf`
  http://oss.metaparadigm.com/apache-privsep/

``` apache
<IfModule !mod_authn_privsep.c>
    LoadModule privsep_module /usr/lib/apache2/modules/mod_privsep.so
    LoadModule authn_privsep_module /usr/lib/apache2/modules/mod_authn_privsep.so
</IfModule>

AuthType Basic
AuthBasicProvider privsep
PrivilegeSeparation On
AuthzUnixgroup on
AuthzUnixgroupAuthoritative off
```

**Comment by tanguy2m** [comment]
**Apache configuration file reference**
- ReadyNas OS 4 file `/etc/frontview/apache/Auth.conf`
```apache
<IfModule authnz_external_module>
    AuthType Basic
    AuthBasicProvider external
    AuthExternal pwauth
</IfModule>

<IfModule !authnz_external_module>
    LoadModule authnz_external_module /usr/lib/apache2/modules/mod_authnz_external.so
    LoadModule auth_sys_group_module /usr/lib/apache2/modules/mod_auth_sys_group.so
    AddExternalAuth pwauth /usr/bin/pwauth
    SetExternalAuthMethod pwauth environment
</IfModule>
```
- ReadyNas OS 6 file `/etc/frontview/apache/Auth.conf`
```apache
<IfModule !mod_authn_privsep.c>
    LoadModule privsep_module /usr/lib/apache2/modules/mod_privsep.so
    LoadModule authn_privsep_module /usr/lib/apache2/modules/mod_authn_privsep.so
</IfModule>

AuthType Basic
AuthBasicProvider privsep
PrivilegeSeparation On
AuthzUnixgroup on
AuthzUnixgroupAuthoritative off
```
