### ISSUE TITLE
Web-apps content administration - P0 functions

### ISSUE THREAD

**Issue by tanguy2m** [tanguy2m/RN6-WebApps#4]
Functions covered:
- **API** > list installed applications
- Config & setup files
  - **API** > list
  - **API** > edit
- **API** > delete web files
- **API** > update all files
- **API** > delete all files
- **Toolbox HMI** > installed applications administration
- **Toolbox HMI** > edit files

***TODO***
- [x] Display something when no file is found
- [ ] **Toolbox HMI**: image URL uses hardcoded VM IP => For installed packages?
- [ ] //admin/{config,setup}/APPNAME/FILE => chmod 775
- [ ] Launch applications from the Toolbox HMI

**Comment by tanguy2m** [comment]
***DESIGN***
